#!/usr/bin/env bash
# =============================================================================
# add-tenant-nginx.sh — Add nginx config for a new tenant subdomain
#
# Usage (run on the server):
#   sudo ./infra/add-tenant-nginx.sh nocoresources
#
# This creates an nginx server block that routes <slug>.entouch.org
# to the same backend (gunicorn on port 5002) and serves the same
# frontend static files. The backend resolves the tenant from the
# Host header.
#
# Prerequisites:
#   - Wildcard SSL cert at /etc/letsencrypt/live/entouch.org/
#     OR the existing entouch.org cert (will work if expanded to include subdomain)
#   - The tenant must already be registered in backend/tenants.json
# =============================================================================

set -euo pipefail

BASE_DOMAIN="entouch.org"
NGINX_AVAILABLE="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
API_PORT=5002
WEB_ROOT="/var/www/sitekeeper/html"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}▶ $*${NC}"; }
die()  { echo -e "${RED}✗ $*${NC}"; exit 1; }

SLUG="${1:-}"
[[ -z "$SLUG" ]] && die "Usage: $0 <tenant-slug>"

DOMAIN="${SLUG}.${BASE_DOMAIN}"
CONF_FILE="${NGINX_AVAILABLE}/${DOMAIN}"

[[ -f "$CONF_FILE" ]] && die "Config already exists: $CONF_FILE"

info "Creating nginx config for $DOMAIN..."

cat > "$CONF_FILE" << EOF
# Tenant: $SLUG
# Auto-generated by add-tenant-nginx.sh

server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name $DOMAIN;

    # Uses the wildcard cert (*.entouch.org) or the main entouch.org cert
    ssl_certificate /etc/letsencrypt/live/$BASE_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$BASE_DOMAIN/privkey.pem;

    # API routes → gunicorn (tenant resolved from Host header)
    location /api/ {
        proxy_pass http://127.0.0.1:$API_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
    }

    # Frontend — same SPA for all tenants
    location / {
        root $WEB_ROOT;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }
}
EOF

info "Enabling site..."
ln -sf "$CONF_FILE" "$NGINX_ENABLED/$DOMAIN"

info "Testing nginx config..."
nginx -t || die "nginx config test failed!"

info "Reloading nginx..."
systemctl reload nginx

info "Done! $DOMAIN is now routing to the backend."
info "The backend will resolve tenant '$SLUG' from the Host header."
