"""SQLAlchemy ORM models for the Contractor Management App.

All primary keys are UUID v4 (generated by PostgreSQL's gen_random_uuid()).
All timestamps use TIMESTAMPTZ so they are stored in UTC.
Cascade deletes are enforced at the database level via ON DELETE CASCADE.

Line item structure (v2):
  LineItem  — a named group (e.g. "Toilet Replacement") with an hourly_rate
    └── LineItemEntry  — either a material (type='material') or hours (type='hours')
        material: name, notes, url, unit_price, quantity  → total = unit_price * quantity
        hours:    name, notes, url, hours                 → cost  = hours * parent.hourly_rate

SavedItem mirrors LineItem and can have SavedItemEntry children.
"""

import uuid

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    Date,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from sqlalchemy.types import TIMESTAMP

from .extensions import db


# ---------------------------------------------------------------------------
# Association tables (many-to-many)
# ---------------------------------------------------------------------------

job_site_contacts = db.Table(
    "job_site_contacts",
    Column(
        "job_site_id",
        UUID(as_uuid=True),
        ForeignKey("job_sites.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "contact_id",
        UUID(as_uuid=True),
        ForeignKey("contacts.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)

job_contacts = db.Table(
    "job_contacts",
    Column(
        "job_id",
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "contact_id",
        UUID(as_uuid=True),
        ForeignKey("contacts.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)

job_employees = db.Table(
    "job_employees",
    Column(
        "job_id",
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "user_id",
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)


# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------


class User(db.Model):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(255), nullable=False, unique=True)
    password_hash = Column(Text, nullable=False)
    name = Column(String(255), nullable=True)
    phone = Column(String(50), nullable=True)
    # Tenant access control
    role = Column(String(20), nullable=False, default="member")  # 'admin' or 'member'
    is_approved = Column(Boolean, nullable=False, default=False)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    job_sites = relationship(
        "JobSite", back_populates="user", cascade="all, delete-orphan"
    )
    saved_items = relationship(
        "SavedItem", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<User {self.email}>"


# ---------------------------------------------------------------------------
# Contact
# ---------------------------------------------------------------------------


class Contact(db.Model):
    __tablename__ = "contacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    phone = Column(String(50), nullable=True)
    email = Column(String(255), nullable=True)
    mailing_address = Column(Text, nullable=True)
    notes = Column(Text, nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    def __repr__(self):
        return f"<Contact {self.name}>"


# ---------------------------------------------------------------------------
# JobSite
# ---------------------------------------------------------------------------


class JobSite(db.Model):
    __tablename__ = "job_sites"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    address = Column(Text, nullable=True)
    default_hourly_rate = Column(Numeric(12, 4), nullable=True)
    primary_contact_id = Column(
        UUID(as_uuid=True),
        ForeignKey("contacts.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    user = relationship("User", back_populates="job_sites")
    primary_contact = relationship("Contact", foreign_keys=[primary_contact_id])
    contacts = relationship(
        "Contact", secondary=job_site_contacts, backref="job_sites"
    )
    jobs = relationship("Job", back_populates="job_site", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<JobSite {self.name}>"


# ---------------------------------------------------------------------------
# Job
# ---------------------------------------------------------------------------


class Job(db.Model):
    __tablename__ = "jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_site_id = Column(
        UUID(as_uuid=True),
        ForeignKey("job_sites.id", ondelete="CASCADE"),
        nullable=False,
    )
    name = Column(String(255), nullable=False)
    status = Column(String(50), nullable=False, default="pending")
    description = Column(Text, nullable=True)
    default_hourly_rate = Column(Numeric(12, 4), nullable=True)
    primary_contact_id = Column(
        UUID(as_uuid=True),
        ForeignKey("contacts.id", ondelete="SET NULL"),
        nullable=True,
    )
    finished_at = Column(TIMESTAMP(timezone=True), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    job_site = relationship("JobSite", back_populates="jobs")
    primary_contact = relationship("Contact", foreign_keys=[primary_contact_id])
    contacts = relationship("Contact", secondary=job_contacts, backref="jobs")
    employees = relationship("User", secondary=job_employees, backref="assigned_jobs")
    notes = relationship("Note", back_populates="job", cascade="all, delete-orphan")
    time_entries = relationship(
        "TimeEntry", back_populates="job", cascade="all, delete-orphan"
    )
    estimates = relationship(
        "Estimate", back_populates="job", cascade="all, delete-orphan"
    )
    invoices = relationship(
        "Invoice", back_populates="job", cascade="all, delete-orphan"
    )
    photos = relationship(
        "JobPhoto", back_populates="job", cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<Job {self.name} [{self.status}]>"


# ---------------------------------------------------------------------------
# Note
# ---------------------------------------------------------------------------


class Note(db.Model):
    __tablename__ = "notes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    body = Column(Text, nullable=False)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    job = relationship("Job", back_populates="notes")

    def __repr__(self):
        return f"<Note {self.id}>"


# ---------------------------------------------------------------------------
# Estimate
# ---------------------------------------------------------------------------


class Estimate(db.Model):
    __tablename__ = "estimates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    title = Column(String(255), nullable=False)
    delivered = Column(Boolean, nullable=False, default=False)
    # tax_rate is stored as a percentage (e.g. 8.5 = 8.5%). NULL = no tax.
    # Tax applies only to material entries, not hours.
    tax_rate = Column(Numeric(6, 4), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    pdf_generated_at = Column(TIMESTAMP(timezone=True), nullable=True)
    pdf_object_key = Column(Text, nullable=True)

    # Document metadata (overridable per-document, defaults from profile)
    document_number = Column(String(50), nullable=True)
    document_date = Column(Date, nullable=True)
    bill_to = Column(Text, nullable=True)
    company_name = Column(String(255), nullable=True)
    user_name = Column(String(255), nullable=True)
    user_phone = Column(String(50), nullable=True)
    user_email = Column(String(255), nullable=True)
    payment_method = Column(String(255), nullable=True)
    business_address = Column(String(500), nullable=True)
    worksite_address = Column(String(500), nullable=True)
    notes = Column(Text, nullable=True)

    # Visibility flags for PDF generation
    show_document_number = Column(Boolean, nullable=False, default=True)
    show_document_date = Column(Boolean, nullable=False, default=True)
    show_bill_to = Column(Boolean, nullable=False, default=True)
    show_company_name = Column(Boolean, nullable=False, default=True)
    show_user_name = Column(Boolean, nullable=False, default=True)
    show_user_phone = Column(Boolean, nullable=False, default=True)
    show_user_email = Column(Boolean, nullable=False, default=True)
    show_payment_method = Column(Boolean, nullable=False, default=True)
    show_business_address = Column(Boolean, nullable=False, default=True)
    show_worksite_address = Column(Boolean, nullable=False, default=True)
    show_notes = Column(Boolean, nullable=False, default=True)
    show_logo = Column(Boolean, nullable=False, default=False)

    job = relationship("Job", back_populates="estimates")
    line_items = relationship(
        "LineItem",
        primaryjoin="and_(LineItem.parent_id == Estimate.id, "
                    "LineItem.parent_type == 'estimate')",
        foreign_keys="LineItem.parent_id",
        cascade="all, delete-orphan",
        overlaps="line_items",
    )
    converted_invoice = relationship(
        "Invoice",
        back_populates="source_estimate",
        foreign_keys="Invoice.source_estimate_id",
    )

    def __repr__(self):
        return f"<Estimate {self.title}>"


# ---------------------------------------------------------------------------
# Invoice
# ---------------------------------------------------------------------------


class Invoice(db.Model):
    __tablename__ = "invoices"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    title = Column(String(255), nullable=False)
    source_estimate_id = Column(
        UUID(as_uuid=True),
        ForeignKey("estimates.id", ondelete="SET NULL"),
        nullable=True,
    )
    delivered = Column(Boolean, nullable=False, default=False)
    # Invoice workflow status: drafting → waiting_to_send → sent_awaiting_payment → paid
    status = Column(String(30), nullable=False, default="drafting")
    # When the current status was set
    status_changed_at = Column(TIMESTAMP(timezone=True), nullable=True, server_default=func.now())
    # tax_rate is stored as a percentage (e.g. 8.5 = 8.5%). NULL = no tax.
    # Tax applies only to material entries, not hours.
    tax_rate = Column(Numeric(6, 4), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    pdf_generated_at = Column(TIMESTAMP(timezone=True), nullable=True)
    pdf_object_key = Column(Text, nullable=True)

    # Document metadata (overridable per-document, defaults from profile)
    document_number = Column(String(50), nullable=True)
    document_date = Column(Date, nullable=True)
    bill_to = Column(Text, nullable=True)
    company_name = Column(String(255), nullable=True)
    user_name = Column(String(255), nullable=True)
    user_phone = Column(String(50), nullable=True)
    user_email = Column(String(255), nullable=True)
    payment_method = Column(String(255), nullable=True)
    business_address = Column(String(500), nullable=True)
    worksite_address = Column(String(500), nullable=True)
    notes = Column(Text, nullable=True)

    # Visibility flags for PDF generation
    show_document_number = Column(Boolean, nullable=False, default=True)
    show_document_date = Column(Boolean, nullable=False, default=True)
    show_bill_to = Column(Boolean, nullable=False, default=True)
    show_company_name = Column(Boolean, nullable=False, default=True)
    show_user_name = Column(Boolean, nullable=False, default=True)
    show_user_phone = Column(Boolean, nullable=False, default=True)
    show_user_email = Column(Boolean, nullable=False, default=True)
    show_payment_method = Column(Boolean, nullable=False, default=True)
    show_business_address = Column(Boolean, nullable=False, default=True)
    show_worksite_address = Column(Boolean, nullable=False, default=True)
    show_notes = Column(Boolean, nullable=False, default=True)
    show_logo = Column(Boolean, nullable=False, default=False)

    job = relationship("Job", back_populates="invoices")
    source_estimate = relationship(
        "Estimate",
        back_populates="converted_invoice",
        foreign_keys=[source_estimate_id],
    )
    line_items = relationship(
        "LineItem",
        primaryjoin="and_(LineItem.parent_id == Invoice.id, "
                    "LineItem.parent_type == 'invoice')",
        foreign_keys="LineItem.parent_id",
        cascade="all, delete-orphan",
        overlaps="line_items",
    )

    def __repr__(self):
        return f"<Invoice {self.title}>"


# ---------------------------------------------------------------------------
# InvoiceStatusHistory
# ---------------------------------------------------------------------------


class InvoiceStatusHistory(db.Model):
    __tablename__ = "invoice_status_history"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    invoice_id = Column(
        UUID(as_uuid=True),
        ForeignKey("invoices.id", ondelete="CASCADE"),
        nullable=False,
    )
    status = Column(String(30), nullable=False)
    changed_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    invoice = relationship("Invoice", backref="status_history")

    def __repr__(self):
        return f"<InvoiceStatusHistory {self.status} @ {self.changed_at}>"


# ---------------------------------------------------------------------------
# LineItem  (v2 — named group with hourly_rate; price is derived)
# ---------------------------------------------------------------------------


class LineItem(db.Model):
    __tablename__ = "line_items"
    __table_args__ = (
        CheckConstraint(
            "parent_type IN ('estimate', 'invoice')",
            name="ck_line_items_parent_type",
        ),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # parent_id references either estimates.id or invoices.id (no FK constraint
    # so it can be polymorphic); integrity enforced at the service layer.
    parent_id = Column(UUID(as_uuid=True), nullable=False)
    parent_type = Column(String(20), nullable=False)
    name = Column(String(255), nullable=False)
    notes = Column(Text, nullable=True)
    # hourly_rate is used by LineItemEntry rows of type 'hours'
    hourly_rate = Column(Numeric(12, 4), nullable=True)
    sort_order = Column(Integer, nullable=False, default=0)

    entries = relationship(
        "LineItemEntry",
        back_populates="line_item",
        cascade="all, delete-orphan",
        order_by="LineItemEntry.sort_order",
    )

    def __repr__(self):
        return f"<LineItem {self.name}>"


# ---------------------------------------------------------------------------
# LineItemEntry  (sub-item under a LineItem)
# ---------------------------------------------------------------------------


class LineItemEntry(db.Model):
    __tablename__ = "line_item_entries"
    __table_args__ = (
        CheckConstraint(
            "entry_type IN ('material', 'hours', 'fee')",
            name="ck_line_item_entries_type",
        ),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    line_item_id = Column(
        UUID(as_uuid=True),
        ForeignKey("line_items.id", ondelete="CASCADE"),
        nullable=False,
    )
    entry_type = Column(String(20), nullable=False)  # 'material' | 'hours'
    name = Column(String(255), nullable=False)
    notes = Column(Text, nullable=True)
    url = Column(Text, nullable=True)

    # Material fields
    unit_price = Column(Numeric(12, 4), nullable=True)
    quantity = Column(Numeric(12, 4), nullable=True)

    # Hours fields
    hours = Column(Numeric(12, 4), nullable=True)

    sort_order = Column(Integer, nullable=False, default=0)

    line_item = relationship("LineItem", back_populates="entries")

    def __repr__(self):
        return f"<LineItemEntry [{self.entry_type}] {self.name}>"


# ---------------------------------------------------------------------------
# SavedItem  (v2 — mirrors LineItem structure)
# ---------------------------------------------------------------------------


class SavedItem(db.Model):
    __tablename__ = "saved_items"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    name = Column(String(255), nullable=False)
    notes = Column(Text, nullable=True)
    hourly_rate = Column(Numeric(12, 4), nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    user = relationship("User", back_populates="saved_items")
    entries = relationship(
        "SavedItemEntry",
        back_populates="saved_item",
        cascade="all, delete-orphan",
        order_by="SavedItemEntry.sort_order",
    )

    def __repr__(self):
        return f"<SavedItem {self.name}>"


# ---------------------------------------------------------------------------
# SavedItemEntry  (sub-item under a SavedItem)
# ---------------------------------------------------------------------------


class SavedItemEntry(db.Model):
    __tablename__ = "saved_item_entries"
    __table_args__ = (
        CheckConstraint(
            "entry_type IN ('material', 'hours', 'fee')",
            name="ck_saved_item_entries_type",
        ),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    saved_item_id = Column(
        UUID(as_uuid=True),
        ForeignKey("saved_items.id", ondelete="CASCADE"),
        nullable=True,  # NULL = standalone entry in Materials Library
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,  # Set for standalone entries; derived from parent for grouped entries
    )
    entry_type = Column(String(20), nullable=False)  # 'material' | 'hours'
    name = Column(String(255), nullable=False)
    notes = Column(Text, nullable=True)
    url = Column(Text, nullable=True)

    # Material fields
    unit_price = Column(Numeric(12, 4), nullable=True)
    quantity = Column(Numeric(12, 4), nullable=True)

    # Hours fields
    hours = Column(Numeric(12, 4), nullable=True)

    sort_order = Column(Integer, nullable=False, default=0)

    saved_item = relationship("SavedItem", back_populates="entries")

    def __repr__(self):
        return f"<SavedItemEntry [{self.entry_type}] {self.name}>"


# ---------------------------------------------------------------------------
# DocumentNumber  (auto-increment tracking for estimates/invoices)
# ---------------------------------------------------------------------------


class DocumentNumber(db.Model):
    __tablename__ = "document_numbers"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_type = Column(String(20), nullable=False)  # 'estimate' or 'invoice'
    next_number = Column(Integer, nullable=False, default=1)

    def __repr__(self):
        return f"<DocumentNumber {self.document_type} next={self.next_number}>"


# ---------------------------------------------------------------------------
# TimeEntry  (clock-in/out or manual hours per user per job)
# ---------------------------------------------------------------------------


class TimeEntry(db.Model):
    __tablename__ = "time_entries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    clock_in = Column(TIMESTAMP(timezone=True), nullable=True)
    clock_out = Column(TIMESTAMP(timezone=True), nullable=True)
    hours = Column(Numeric(8, 4), nullable=True)
    worked_at = Column(TIMESTAMP(timezone=True), nullable=True)
    note = Column(Text, nullable=True)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    job = relationship("Job", back_populates="time_entries")
    user = relationship("User", backref="time_entries")

    def __repr__(self):
        return f"<TimeEntry job={self.job_id} user={self.user_id}>"


# ---------------------------------------------------------------------------
# JobPhoto  (media uploads per job, stored in MinIO)
# ---------------------------------------------------------------------------


class JobPhoto(db.Model):
    __tablename__ = "job_photos"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    uploaded_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    object_key = Column(Text, nullable=False)
    filename = Column(String(255), nullable=False)
    content_type = Column(String(100), nullable=False)
    file_size = Column(Integer, nullable=False)
    created_at = Column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    job = relationship("Job", back_populates="photos")
    uploader = relationship("User", foreign_keys=[uploaded_by])

    def __repr__(self):
        return f"<JobPhoto {self.filename}>"


# ---------------------------------------------------------------------------
# DocumentPhoto  (junction: links job_photos to estimates/invoices)
# ---------------------------------------------------------------------------


class DocumentPhoto(db.Model):
    __tablename__ = "document_photos"
    __table_args__ = (
        CheckConstraint(
            "document_type IN ('estimate', 'invoice')",
            name="ck_document_photos_type",
        ),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_id = Column(UUID(as_uuid=True), nullable=False)
    document_type = Column(String(20), nullable=False)
    photo_id = Column(
        UUID(as_uuid=True),
        ForeignKey("job_photos.id", ondelete="CASCADE"),
        nullable=False,
    )
    sort_order = Column(Integer, nullable=False, default=0)

    photo = relationship("JobPhoto")

    def __repr__(self):
        return f"<DocumentPhoto doc={self.document_id} photo={self.photo_id}>"


# ---------------------------------------------------------------------------
# BusinessInfo  (tenant-level settings — one row per tenant database)
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# DocumentFieldSettings  (tenant-level field visibility config)
# ---------------------------------------------------------------------------


class DocumentFieldSettings(db.Model):
    __tablename__ = "document_field_settings"
    __table_args__ = (
        db.UniqueConstraint("document_type", "field_key", name="uq_doc_field_settings_type_key"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_type = Column(String(20), nullable=False)  # 'estimate' or 'invoice'
    field_key = Column(String(50), nullable=False)
    visibility = Column(String(20), nullable=False, default="always_show")  # 'always_show', 'additional', 'disabled'
    pdf_visible = Column(Boolean, nullable=False, default=True)

    def __repr__(self):
        return f"<DocumentFieldSettings {self.document_type}.{self.field_key}={self.visibility}>"


# ---------------------------------------------------------------------------
# BusinessInfo  (tenant-level settings — one row per tenant database)
# ---------------------------------------------------------------------------


class BusinessInfo(db.Model):
    __tablename__ = "business_info"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    business_name = Column(String(255), nullable=True)
    state = Column(String(2), nullable=True)
    payment_method = Column(String(255), nullable=True)
    business_address = Column(String(500), nullable=True)
    business_phone = Column(String(50), nullable=True)
    business_email = Column(String(255), nullable=True)
    owner_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    default_hourly_rate = Column(Numeric(12, 4), nullable=True)
    logo_object_key = Column(Text, nullable=True)
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    owner = relationship("User", foreign_keys=[owner_user_id])

    def __repr__(self):
        return f"<BusinessInfo {self.business_name}>"
