#!/usr/bin/env bash
# =============================================================================
# Platform Migration 003: Replace per-tenant nginx configs with a wildcard.
#
# This script:
# 1. Writes a single wildcard server block for *.jobsyte.app
# 2. Archives old per-tenant configs
# 3. Removes their symlinks from sites-enabled
# 4. Enables the new wildcard config
# 5. Tests and reloads nginx
#
# Idempotent: checks if wildcard already exists before acting.
#
# MUST be run with sudo on the production server.
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}▶ $*${NC}"; }
die()  { echo -e "${RED}✗ $*${NC}"; exit 1; }

WILDCARD_CONF="/etc/nginx/sites-available/jobsyte.app-wildcard"
ARCHIVE_DIR="/etc/nginx/sites-available/archived"

# Already done?
if [[ -f "$WILDCARD_CONF" ]]; then
    info "Wildcard config already exists at $WILDCARD_CONF — nothing to do."
    exit 0
fi

info "Creating nginx wildcard config for *.jobsyte.app..."

# Create archive directory
mkdir -p "$ARCHIVE_DIR"

# Archive and unlink old per-tenant configs
OLD_CONFIGS=(
    "jobsyte.app"
    "nocoresources.jobsyte.app"
    "camtest.jobsyte.app"
    "tilecraft.jobsyte.app"
    "demo.jobsyte.app"
)

for conf in "${OLD_CONFIGS[@]}"; do
    if [[ -f "/etc/nginx/sites-available/$conf" ]]; then
        info "  Archiving: $conf"
        mv "/etc/nginx/sites-available/$conf" "$ARCHIVE_DIR/$conf"
    fi
    if [[ -L "/etc/nginx/sites-enabled/$conf" ]] || [[ -f "/etc/nginx/sites-enabled/$conf" ]]; then
        info "  Removing symlink: sites-enabled/$conf"
        rm -f "/etc/nginx/sites-enabled/$conf"
    fi
done

# Write the wildcard config
cat > "$WILDCARD_CONF" << 'NGINX'
# JobSyte wildcard config — handles all *.jobsyte.app subdomains
# Auto-generated by infra/platform_migrations/003_nginx_wildcard.sh

server {
    listen 80;
    server_name jobsyte.app www.jobsyte.app *.jobsyte.app;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name jobsyte.app www.jobsyte.app *.jobsyte.app;

    ssl_certificate /etc/letsencrypt/live/jobsyte.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jobsyte.app/privkey.pem;

    # API routes → gunicorn (tenant resolved from Host header by Flask)
    location /api/ {
        proxy_pass http://127.0.0.1:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        client_max_body_size 25M;
    }

    # Frontend SPA — same build for all tenants
    location / {
        root /var/www/sitekeeper/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
NGINX

info "Enabling wildcard config..."
ln -sf "$WILDCARD_CONF" /etc/nginx/sites-enabled/jobsyte.app-wildcard

info "Testing nginx configuration..."
if ! nginx -t 2>&1; then
    die "nginx config test failed! Restoring old configs..."
    # In case of failure, restore from archive
    for conf in "${OLD_CONFIGS[@]}"; do
        if [[ -f "$ARCHIVE_DIR/$conf" ]]; then
            mv "$ARCHIVE_DIR/$conf" "/etc/nginx/sites-available/$conf"
            ln -sf "/etc/nginx/sites-available/$conf" "/etc/nginx/sites-enabled/$conf"
        fi
    done
    rm -f "$WILDCARD_CONF" "/etc/nginx/sites-enabled/jobsyte.app-wildcard"
    nginx -t && systemctl reload nginx
    die "Rolled back to per-tenant configs."
fi

info "Reloading nginx..."
systemctl reload nginx

info "Done! All *.jobsyte.app subdomains now handled by the wildcard config."
info "Old configs archived to: $ARCHIVE_DIR/"
